Helper function was using Def__MyL2DepositedERC20 instead of the optimism contracts OVM_L1ERC20Gateway_Def
ethereum-optimism/optimism-tutorial pull request #13
Opened 2021-03-26 12:51 UTC by juanfranblanco

**Description**
Helper function was using Def__MyL2DepositedERC20 instead of the optimism contracts OVM_L1ERC20Gateway_Def

2021-03-26 20:17 UTC, platocrat commented on scripts/helpers.ts
> +        OVM_L1ERC20Gateway = new Contract(l1ERC20GatewayAddress, OVM_L1ERC20Gateway_Def.abi, l1Wallet)
this looks great 👍

2021-03-26 20:18 UTC, platocrat commented on scripts/helpers.ts
> +        const OVM_L1ERC20Gateway_Def = getContractDefinition('OVM_L1ERC20Gateway', false);
To avoid the confusion thought readers may get, I think it's best to get the name of the contract definition the same, as `Def__MyL2DepositedERC20`

2021-03-26 20:22 UTC, platocrat commented on scripts/helpers.ts
>          OVM_L2DepositedERC20 = new Contract(l2ERC20GatewayAddress, Def__MyL2DepositedERC20.abi, l2Wallet)
Any reason why you didn't update the other instance of `Def__MyL2DepositedERC20`?

This shouldn't be an issue if you revert the name of `OVM_L1ERC20Gateway_Def`.

2021-03-26 20:23 UTC, platocrat requested changes
Just change the name `OVM_L1ERC20Gateway_Def` back to `Def__MyL2DepositedERC20`.

Besides that, this looks good to me

2021-03-30 16:08 UTC, juanfranblanco commented
@platocrat sorry I did not see the notification.
```To avoid the confusion thought readers may get, I think it's best to get the name of the contract definition the same, as Def__MyL2DepositedERC20```

The issue is that the definition used is from the "optimism contracts" node modules, so it is using the the same way to get the contract definitions as other parts in the code.

```Any reason why you didn't update the other instance of Def__MyL2DepositedERC20```
The problem surfaced mainly as the abi was incorrect, so this was not an issue in the past, but only surfaced when trying to access "l2DepositedToken" using the abi from Def__MyL2DepositedERC20.

2021-03-30 16:10 UTC, juanfranblanco commented
```Just change the name OVM_L1ERC20Gateway_Def back to Def__MyL2DepositedERC20.```
That is exactly the problem, we want the L1 Gateway ABI.

2021-03-30 17:51 UTC, K-Ho commented
Amazing catch @juanfranblanco - lgtm

2021-03-30 17:52 UTC, merged