Update the Hardhat tutorial to OVM 2.0
ethereum-optimism/optimism-tutorial pull request #64
Opened 2021-10-08 18:14 UTC by qbzzt

Closing: INT-127

2021-10-08 18:22 UTC, K-Ho requested changes
I'd request we do this right and actually nail down the end-to-end devex for spinning up a local network rather than adding hacks into our official tutorial

2021-10-08 18:22 UTC, K-Ho commented on hardhat/README.md
> +   wget https://raw.githubusercontent.com/ethereum-optimism/optimism-tutorial/20211008-ovm20/ovm20-temp/docker-compose-ovm20.yml
Is this really what we want as part of the devex of spinning up getting started project?

2021-10-08 18:22 UTC, K-Ho commented on ovm20-temp/docker-compose-ovm20.yml
> +# TODO: Prefix all env vars with service name
Why does this live here? I'd rather do this the right way and not need to include a docker compose file in our simple getting started tutorial

2021-10-15 20:34 UTC, SmitV commented on hardhat/README.md
> +   Not that until we officially release OVM 2.0 you need to clone the `regenesis/0.5.0`
_Note_ :)

2021-10-15 21:09 UTC, merged